config/routes.rb
Rails.application.routes.draw do

  root "auctions#index"
  resources :users, only: [:new, :create]
  resources :auctions, only: [:index, :new, :create, :show] do
    resources :bids
    resources :reservings, only: [:create]
  end



  resources :sessions, only: [:new, :create, :destroy] do
    delete :destroy, on: :collection  #on: :collection make the delete not require an id
  end

end

app/models/auction.rb
class Auction < ActiveRecord::Base
  belongs_to :user
  has_many :bids, dependent: :destroy

  validates :title, presence: true
  validates :price, presence: true
  validates :end_date, presence: true

  include AASM

  aasm whiny_transitions: false do
    state :published, initial: true
    state :reserved
    state :won
    state :canceled
    state :not_reserved

    event :reserve do
      transitions from: :published, to: :reserved
    end
    #
    # event :win do
    #   transitions from: :reserved, to: :won
    # end
    #
    # event :cancel do
    #   transitions from: [:published, :reserved], to: :canceled
    # end
    #
    # event :not_reserve do
    #   transitions from: :published, to: :not_reserved
    # end

  end



end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :auction
  belongs_to :user

  # validates :amount, presence: true, numericality: {greater_than: cur_price}
  # validate :bid_price_must_be_higher_than_the_current_price
  #
  # def bid_price_must_be_higher_than_the_current_price
  #   if auction.bids.maximum(:amount) > bid.amount
  #     errors.add(:amount, "must be greater than current price")
  #   end
  # end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :auctions, dependent: :destroy
  has_many :bids, dependent: :destroy

  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  # validates :email, presence: true, format: VALID_EMAIL_REGEX

  validates :email, presence: true, format: VALID_EMAIL_REGEX
  validates :fullname, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_user
    redirect_to new_session_path, notice: "Please sign in!" unless user_signed_in?
  end

  # def authenticate_user
  #   redirect_to new_user_path, notice: "Please sign in!" unless user_signed_in?
  # end

  def user_signed_in?
    current_user.present?
  end
  helper_method :user_signed_in?

  def current_user
    @current_user ||= User.find_by_id session[:user_id] if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :authenticate_user, except: [:index]
  before_action :find_auction, only: [:edit, :update, :destroy, :show]

  def index
    @auctions = Auction.all
  end

  def show
    @bid = Bid.new
    @current_price= @auction.bids.maximum(:amount)
  end

  def new
    @auction = Auction.new
  end

  def create
    # @auction.end_date = Date.parse(params(:end_date)).strftime("%Y-%m-%d")
    # puts "date-params: #{params[:end_date]}"
    @auction = Auction.new auction_params
    @auction.user = current_user
    # puts @auction.inspect
    # render text: auction_params

    if @auction.save
      redirect_to auction_path(@auction)
    else
      render :new
    end
  end



  private

  def find_auction
    @auction = Auction.find params[:id]
  end

  def auction_params
    params.require(:auction).permit(:title, :detail, :end_date, :price)
  end

end

app/controllers/bids_controller.rb
class BidsController < ApplicationController

  before_action :authenticate_user

  def create
    bid_params = params.require(:bid).permit(:amount)
    @auction = Auction.find params[:auction_id]
    if (@auction.bids.empty?)
      @current_price = 0
    else
      @current_price = @auction.bids.maximum(:amount)
    end
    @bid = current_user.bids.new(bid_params)
    @bid.auction = @auction

    # puts "CURRENT PRICE: #{@current_price}"

    # curr_bid = bid_params[:amount].to_f
    # @auction.bids.last ? max_bid = .to_f : max_bid = 0
    # puts "auction last bid : #{last_bid}"
    # puts "current bid: #{curr_bid}"
    # render text:bid_params

    if (@current_price < @bid.amount)
      if @bid.save
        redirect_to auction_path(@auction)
      else
        flash[:alert] = @bid.errors.full_messages.join(", ")
        # redirect_to auction_path(@auction)
        render "auctions/show"
      end
    else
      flash.now[:alert] = "Bidding amount should be higher that current price !!"
      # redirect_to auction_path(@auction)
      render "auctions/show"
      # render auction_path(@auction)
    end

  end
end

app/controllers/reservings_controller.rb
class ReservingsController < ApplicationController

  before_action :authenticate_user

  def create
    auction = Auction.find params[:auction_id]
    if auction.reserve
      auction.save
      redirect_to auction, notice: "Auction Published!"
    else
      redirect_to auction, alert: "Error! Can't publish auction"
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email params[:email]
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to(root_path)
    else
      # render nothing: true
      flash[:alert] = "Wrong credentials!"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
    # render nothing: true
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit([:fullname, :email,
                                                :password, :password_confirmation])
    user = User.new user_params
    if user.save
      session[:user_id] = user.id
      redirect_to root_path, notice: "account created"
    else
      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper
  def label_class(state)
    case state
    when "published"
      "label-default"
    when "reserved"
      "label-primary"
    when "won"
      "label-success"
    when "canceled"
      "label-danger"
    when "not_reserved"
      "label-warning"
    end
  end

end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/reservings_helper.rb
module ReservingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/auctions/_form.html.erb
<% if !@auction.errors.empty? %>
    <div class="red-sm">Error (s) :
      <%= @auctions.errors.full_messages.join(", ") %> !!
    </div>
  <% end %>

  <%= simple_form_for(@auction, html: {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
      <%= f.input :title, class: "form-control", placeholder: "title" %>
    </div>
    <div class="form-group">
      <%= f.input :detail, class: "form-control", placeholder: "input detail description ..", rows: "4"%>
    </div>
    <div class="form-group">
      <%= f.input :end_date, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.input :price, class: "form-control", placeholder: "0" %>
    </div>
    <div class="form-group">
        <%= f.submit(class: "btn btn-primary") %>
        <%= link_to 'Cancel', auctions_path, class:"btn btn-primary" %>
    </div>
  <% end %>

app/views/auctions/index.html.erb
<h1>AUCTION INDEX</h1>
<% @auctions.each do |auction| %>
  <div class="well">
    <%= link_to auction.title, auction_path(auction) %>
  </div>
<% end %>

app/views/auctions/new.html.erb
<div class="col-md-10 col-md-offset-1 top-50">
  <h1 class="oswald font-37">CREATE NEW AUCTION</h1>
    <div class="form-wall">
      <%= render "form" %>
    </div>
</div>

app/views/auctions/show.html.erb
<h1><%= @auction.title %></h1>
<p class="well"><%= @auction.detail %></p>
<h3>Current Price: <%= @current_price %></h3>
<p><span class="label <%= label_class(@auction.aasm_state) %>"><%= @auction.aasm_state.capitalize %></span></p>

<% if (@current_price.to_f > @auction.price.to_f) %>
  <% if @auction.may_reserve? %>
    <%= link_to "Reserve", auction_reservings_path(@auction),
          method: :post,
          data: {confirm: "Are you sure want to reserve?"},
          class: "btn btn-primary" %>
  <% end %>
<% else %>
  <p>Reserve Price Not Met</p>
<% end %>

<%# bidding ----------------------------------------------------------------- %>
<% if !@auction.reserved? %>
  <% if (current_user.id != @auction.user_id) %>
    <%= simple_form_for [@auction, @bid] do |f| %>
      <%= f.input :amount, as: :integer %>
      <%= f.submit "Bid" %>
    <% end %>
  <% end %>
  <hr>
  Previous bid:
  <br>
  <% @auction.bids.each do |bid| %>
    <% if bid.id != @auction.bids.last.id %>
    <div class="well">
      <%= bid.user.fullname.capitalize %>
      bid <b><%= number_to_currency(bid.amount) %></b>
      at <%= bid.created_at.strftime("%b %d, %Y at %I:%M %P") %>
    </div>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Biddr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <nav>
      <%= link_to "HOME", root_path %>
      <%= link_to "New auction", new_auction_path %>
      <div class="pull-right">
        <% if user_signed_in? %>
          Welcome <%= current_user.fullname.capitalize %> |
          <%= link_to "Logout", sessions_path, method: :delete %>
        <% else %>
          <%= link_to "sign in", new_session_path %>
          <%= link_to "sign up", new_user_path %>
        <% end %>
      </div>
    </nav>

    <%#= flash || notice %>
    <% if flash[:notice] %>
      <div class="alert alert-success"><%= flash[:notice] %></div>
    <% elsif flash[:alert] %>
      <div class="alert alert-danger"><%= flash[:alert] %></div>
    <% end %>

    <%= yield %>
  </div>

  <script type="text/javascript">
  $(document).ready(function(){
    setTimeout(function(){
      $('.alert').remove();
    }, 3000);
   })
  </script>

</body>
</html>

app/views/users/index.html.erb
<h1>USER INDEX</h1>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= simple_form_for @user do |f| %>
  <%= f.input :fullname %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.submit %>
<% end %>